name: Verify Docker Compose Images

on:
  push:
    paths:
      - '**.yaml'

jobs:
  verifyImages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: alexellis/setup-arkade@v3
      - name: Verify chart images
        id: verify_images
        run: |
          VERBOSE=true make verify-compose
